name:                cheonjae
version:             0.1.0.0
github:              "ropwareJB/cheonjae"
license:             BSD3
author:              "Joshua Brown"
maintainer:          "gh@ropware.com"
copyright:           "2023 Josh Brown"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cheonjae#readme>

dependencies:
- base >= 4.7 && < 5
- req
- aeson
- bytestring
- utf8-string
- wreq
- lens
- containers
- http-client
- http-client-tls
- tls
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cheonjae:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cheonjae

tests:
  cheonjae-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cheonjae
